### ISSUE TITLE
Test if search tests work

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/wikimedia-content-adapter#8]
I updated the search tests pythonpackage to the latest merges.
Can you run a build to see if the test run through?

**Comment by Charle42** [comment]
The test don't run through and here still are json decoding errors, but there are lesser.
There must be an other reason for them.
Shall i post you the error logs?

**Comment by niccokunzmann** [comment]
Yes, please post the logs

**Comment by Charle42** [comment]
It looks like some thing went worng be testing invalid Headers.


test log : [travis](https://travis-ci.org/schul-cloud/wikimedia-content-adapter)

**Comment by niccokunzmann** [comment]
- id muss ein string sein: https://travis-ci.org/schul-cloud/wikimedia-content-adapter/builds/267540616#L5773
- error code 406 wird zurück gegeben obwohl der content type akzeptiert wird. https://travis-ci.org/schul-cloud/wikimedia-content-adapter/builds/267540616#L5569
- es muss einen parameter "Q" geben, sonst muss man einen Fehler melden. https://travis-ci.org/schul-cloud/wikimedia-content-adapter/builds/267540616#L4485

**Comment by Charle42** [comment]
das erste hatte ich schon gefixt nur nicht gepusht.

in der 2. von dir angegebene Zeile sagt er das er ein sein `accept = */*` ist und ein 406 zurückbekommt aber wenn ich die Abfrage genauso stelle, spricht im header accept auch` */*` explizit angebe, bekomme ich ohne searchproxy dazwischen eine Valide Antwort. 

die 3. Zeile ist ein Anfragefehler -> eine Anfrage an den Service muss ein Q Parameter haben das soll ja grade getestet werden wie der Service dann reagiert 
Wir hatten uns schon mal darüber unterhalten das diese Fehlermeldungen nicht angezeigt werden sollen, wenn man als Test aus führt.

**Comment by niccokunzmann** [comment]
Hi, ich versuche darzulegen, was ich verstanden habe:

Zu 2) 

```
$ curl -i 'http://localhost:3000/v1?sort=-url%2Ctitle&Q=test'
HTTP/1.1 406 Not Acceptable
X-Powered-By: Express
Content-Type: application/vnd.api+json; charset=utf-8
Content-Length: 306
ETag: W/"132-SdWdX9og6z7FJBug0wv+E0WkoII"
Date: Wed, 23 Aug 2017 14:45:15 GMT
Connection: keep-alive

{"jsonapi":{"version":"1.0","meta":{"name":"wikimedia-content-adapter","source":"https://github.com/schul-cloud/wikimedia-content-adapter","description":"This is an adpter for media-file search on wikimedia."}},"errors":[{"status":"406","title":"Not Acceptable","detail":"Content type is not Acceptable"}]}
```
Der Fehler sagt: "Obwohl der content type acceptable ist, kommt eine 406 aber 406 ist für den Content type fehler reserviert."

zu 3) 

https://github.com/schul-cloud/resources-api-v1/#search-api sagt, dass Q verlangt wird
https://github.com/schul-cloud/resources-api-v1/tree/master/schemas/search-response#description zitiert die JSONAPI-Referenz: "If the server does not support sorting as specified in the query parameter sort, it MUST return 400 Bad Request"
400 ist für falsche Anfragen mit invaliden Parametern. Kein Q zu haben ist invalide Parameter zu senden.

Was denkst du: Verstehst du das auch so? Sollten wir es umformulieren?

**Comment by Charle42** [comment]
zu 2) ja das ist anscheind doch ein falscher response. das schau ich mir noch mal an.

zu 3) ahhh Sort-Parameter wird da noch abgefragt. Der wird nicht unterstützt also müsste er ja dann eigendlich 400 zurück senden 

Nee das finde ich schon gut formuliert so, war mir nur nicht klar das es diesen sort param mit abgefragt wird.
