### ISSUE TITLE
Add dockerhub build badge

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/wikimedia-content-adapter#9]
This service is automatically built on dockerhub.
Please add a build badge (fail/success) with a link to:
https://hub.docker.com/r/schulcloud/wikimedia-content-adapter/builds/

**Comment by szymczakk** [comment]
Hi, can I take it? If it's still free please look at #11

**Comment by niccokunzmann** [comment]
Thanks to @szymczakk  and @MattMattV, this issue can be closed now.
